//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int ID_Nota { get; set; }
        public double Nota1 { get; set; }
        public double Nota2 { get; set; }
        public double Nota3 { get; set; }
        public double Promedio { get; set; }
        public string Materia { get; set; }
        public string Estado { get; set; }
        public int ID_Alumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
